examples/dotnet/template.yaml, examples/go/template.yaml, examples/java/template.yaml, examples/node/template.yaml, examples/python/template.yaml
Refer to published layer ARNs so examples work for external customers.
=> Set layer ARNs to published layers

examples/node/newrelic-example-node/package.json
=> fix: Update axios version in node example

checks/startupCheck.go, checks/startupcheck_test.go, main.go
A quick sketch setting up the framework for the startup checks. Tests forthcoming.
=> Set up the startup check framework

checks/startupCheck.go, checks/vendor_check.go, checks/vendor_check_test.go, util/path.go, util/path_test.go
=> Add Vendor Check

checks/sanity_check.go, checks/sanity_check_test.go, checks/startupCheck.go, credentials/credentials.go, credentials/credentials_test.go, util/env.go, util/env_test.go
=> Add Sanity Check

main.go
Draft PR while we're working this out.
=> fix: Expand timeout detection window

README.md
=> Update README With Startup Check Usage

.circleci/config.yml, .gitignore, Makefile, README.md, coverage.sh
Codecov is giving an error because it has no base branch to compare this to for coverage diffing.
=> Add Coverage Reporting

Makefile, telemetry/client_test.go
Also, check for races in `make test`
=> Fix race in unit test

checks/sanity_check.go, checks/sanity_check_test.go, credentials/credentials.go, credentials/credentials_test.go
=> Fix Secrets Manager License Key Check

README.md
=> Update README to Correctly Reflect Default Enablement Mode

examples/sam/java/NewRelicExampleJava/pom.xml, examples/sam/java/NewRelicExampleJava/src/main/java/com.newrelic.lambda.example/App.java, examples/sam/java/README.md, examples/sam/java/template.yaml
Updating java example to use new layer - https://newrelic.atlassian.net/browse/LAMBDA-1236
=> Java layer example update

examples/sam/go/README.md
=> Update Golang Example With Required aws-lambda-go Version

checks/runtime_check.go, checks/runtime_check_test.go, examples/sam/java/deploy.sh, examples/sam/java/template.yaml, util/extension.go
Closes #96
This will still log the error if in debug mode.
=> Silence Errors On Agent Version Check Connectivity Issues

examples/sam/distributedtracing/deploy.sh, examples/sam/dotnet/deploy.sh, examples/sam/go/deploy.sh, examples/sam/java/deploy.sh, examples/sam/node/deploy.sh, examples/sam/python/deploy.sh
Also adds quotes around `${...}` to avoid globbing.
=> Format SAM Deploy Scripts, Remove Debugging

.circleci/config.yml
CI convenience images were out of date. 
=> feat: Updated CircleCI images

.circleci/config.yml
these keys are replaced by a user key generated with a robot account
=> Update config.yml: remove unused keys

checks/sanity_check.go, checks/sanity_check_test.go, config/config.go, config/config_test.go, credentials/credentials.go, credentials/credentials_test.go
Resolves https://github.com/newrelic/newrelic-lambda-extension/issues/94
=> Support loading license key from SSM Parameter Store

util/extension.go
=> update version of extension

util/extension.go
Release new version of Extension v2.3.13
=> release v2.3.13

checks/handler_check.go
As per [aws docs](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html),  `AWS_EXECUTION_ENV` is not available for os-only runtime. Using `AWS_EXECUTION_ENV` env variable, we detect if it is container image lambda so handler check is handled appropriately.
=> docker handler warning issue

README.md, util/extension.go
- update readme to add information about environment variable to ignore Extension checks
- update version for Extension to `2.3.14`
=> Release v2.3.14

examples/terraform/nodejs/lambda-policy.json, examples/terraform/python/lambda-policy.json, examples/terraform/ruby/lambda-policy.json
This PR is raised to address query about least privilege for i am role.
=> feat: Policy update as per IAM least privilege

util/extension.go
Updated version to release Extension `v2.3.16`
=> Release Extension v2.3.16

util/extension.go
=> extension v2.3.17

apm/log_api.go, checks/startup_check.go, checks/startup_check_test.go, main.go, telemetry/client.go, telemetry/client_test.go
Add log API to send function, extension logs to New Relic
=> add log API

apm/apm_payload.go
data parsing resolved for nodejs lambda payload
=> data parsing resolved for nodejs lambda payload

apm/apm_payload.go
updated the code to add trimspace
=> updated the code to add trimspace

examples/sam/java/template.yaml, examples/sam/node/template.yaml, examples/sam/python/template.yaml, examples/sam/ruby/newrelic_example_ruby/app.rb, examples/sam/ruby/template.yaml
**Details** : Fixed the Layer for Ruby with the Latest version.
=> feat: Updated Ruby Example

main.go
-  Updated code to resolve  `task timed out` issue where we are getting long number in `NR UI` instead of `timed out` duration. 
- Tested the extension by building custom layer 
- Tested with concurrent users
=> chore: updating timeout error code

examples/sam/ai-monitoring/README.md
- This PR updates the readme for example.
=> chore: udpate readme for AI monitoring in response streaming example

apm/collector.go
=> Add collector host for prod

apm/connect.go
=> Apm fusion

local_testing/newrelic_lambda_wrapper.py
- This PR aims to update newrelic_lambda_wrapper code similar to code in `newrelic-lambda-layer` repo. So this will help us to get all the test changes with `NEW_RELIC_PACKAGE_REPORTING_ENABLED:false` by default in env.
=> chore: updating local testing newrelic_lambda_wrapper code

lambda/logserver/logserver.go, lambda/logserver/logserver_test.go
This pull request addresses the log handling functionality by recognizing and processing two distinct log formats: `Plain Text` and `JSON`. I have enhanced the code to manage these formats effectively. Additionally, I have updated the test cases to improve coverage and facilitate initial testing.
Added logic to implicitly detect and handle Plain Text logs formatted with tab separation.
Implemented parsing of JSON-formatted logs for structured data extraction.
**Cold Start**: Validated log handling performance during initial application start-up conditions.
**Warm Start**: Ensured parsing logic consistency and efficiency during normal application operation across continuous runs.
**Concurrent Testing**: Verified the correctness and reliability of log handling under concurrent request …
=> chore: update logic to handle request id from AWS function logs

lambda/logserver/logserver.go
- This PR Improves code style consistency by adding a blank line before the ExtractRequestId function, matching the pattern used elsewhere in this file.
=> chore: updated logserver.go

lambda/logserver/logserver.go
Reverts newrelic/newrelic-lambda-extension#301
=> Revert "chore: updated logserver.go"

Makefile
=> update build for GLIBC

util/extension.go
=> extension v2.3.20

util/extension.go
Reverts newrelic/newrelic-lambda-extension#314
=> Revert "extension v2.3.20"

util/extension.go
- This PR updates extension version from `2.3.19` to `2.3.20`
=> feat: updated extension version to 2.3.20

util/extension.go
Update Extension version extension_v2.3.23
=> extension_v2.3.23

util/extension.go
=> extension_v2.3.24

apm/connect.go, checks/runtime_config.go
=> Apm fusion ruby support

.github/workflows/security-scan.yml
- Adding code to scan only `go.mod` and `go.sum` files for dependency scanning
=> feat: Enhance security scan workflow to focus on specific Go mod
