newrelic/newrelic-lambda-extension

lambda/extension/client/client.go, telemetry/client.go, telemetry/client_test.go, telemetry/request.go
The registration response is documented to include the
function name, and we rely on that. But apparently, it's blank
right now.
=> Workaround for missing function name

checks/agentVersionCheck_test.go, checks/handlerCheck_test.go, checks/runtimeCheck_test.go
Also asserts that `os.Getwd()` doesn't return an error.
=> Make Sure Current Working Directory Isn't Root

telemetry/client.go
Removed code that was implemented in the pr for this fix. Have validated that fix is working in all regions - [example query](https://staging.one.nr/0x0jlVkOwWM)
=> Removing functionName workaround

main.go, telemetry/client.go, telemetry/client_test.go, util/extension.go
Go's HTTP client uses a Readable as the request body type, so a request
object is mutated in sending it. Which is more than a little surprising.
=> Rewrite retries to recreate the request from the byte array

checks/runtimeCheck.go, checks/runtimeCheck_test.go
Ideally, tests (and runtime) wouldn't depend on third-party services.
Certainly, the unit tests should not fail when the third-party service
is sending 429 errors
=> Fix unit tests

checks/agentVersionCheck.go, checks/agentVersionCheck_test.go, checks/runtimeCheck.go, checks/runtimeConfig.go
Replacing `libraries.io` agent version check with `github`
Github redirects `releases/latest` requests to the latest tag so I'm preventing the redirect here and pulling the tag version from the redirect url. 
https://newrelic.atlassian.net/browse/LAMBDA-1113
=> Replacing libraries.io with github

credentials/credentials.go, credentials/credentials_test.go, util/extension.go
Customers often mess up the format of the secret. We need to validate it
more carefully.
=> fix: More strict license key secret validation

lambda/logserver/logserver.go
This should prevent a race during shutdown that can lead to a panic
=> Shut down the log server before the channels it writes

main.go, util/extension.go
For LAMDBA-1100. Customers were concerned by the term "failed".
=> Revise debug log message

examples/sam/dotnet/deploy.sh, examples/sam/dotnet/template.yaml, examples/sam/go/template.yaml
We updated the SAM templates to include the region for the s3 bucket...except in the dotnet example. And this updates the extension version to 12. 
=> fix: Update .NET sam template with bucket region, update ext versions

main.go, main_test.go, telemetry/client.go
This further tweaks timeout handling by turning the `DeadlineMS` into a hard timeout and a soft timeout (deadline minus 100ms). We use the hard timeout for transport and the soft timeout for impending timeout detection. This pull request also adds a test to simulate an unresponsive collector to ensure that the extension handles this case gracefully.
=> Add Hard/Soft Timeouts Based On Lambda Deadline

lambda/logserver/logserver.go, lambda/logserver/logserver_test.go, util/extension.go
This is a bit risky, in that it assumes that we'll get requests in order. I don't think we can do better though, as function log records just don't contain the requestId.
=> Maintain lastRequestId across log requests

checks/runtime_config.go
This very small commit should be all that's needed to add Python 3.9 support to the Extension.
=> fix: Adding python 3.9 path to runtime config.

lambda/logserver/logserver.go, lambda/logserver/logserver_test.go, util/extension.go
Making this a draft to solicit suggestions for a better way to handle this scenario.
There's a user report of an extension panic in a Go-instrumented Lambda, when the logserver attempts to parse the platform.start log line for requestId--this particular message's `record` field is apparently a string, rather than the expected map. Log messages show this type mismatch, and the [Lambda Logs API doc](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-logs-api.html) shows some examples (such as platform.fault) for which record can be a string. 
This PR attempts to handle either case. 
https://newrelic.atlassian.net/browse/LAMBDA-1321
=> fix: Handle log event.Record that's a string instead of a map

lambda/logserver/logserver.go, lambda/logserver/logserver_test.go
This may address GTSE-11166, in which a panic occurs if the logs API delivers platform logs/metrics as a string instead of a map.
=> fix: Initial attempt at handling platform logs as string

examples/terraform/nodejs/main.tf, examples/terraform/python/main.tf
Added **NEW_RELIC_LAMBDA_EXTENSION_ENABLED** environment variables in TF examples - if the ingestion for the instrumented function's telemetry data is shipped via newrelic-lambda extension.
=> Add required envs for lambda extensions in TF examples

Makefile, examples/sam/node/deploy.sh, examples/sam/node/template.yaml, main.go, telemetry/batch.go, telemetry/batch_test.go, util/extension.go
The most critical aspect of this fix is subtle: we don't get invoked function ARNs in shutdown events, and we can't send telemetry without one of those (LLC rejects it). We were losing all our buffered telemetry at shutdown because of this. 
I've also simplified timeout handling, and moved the happy-path telemetry send in parallel with our wait on the named pipe. In the normal case of a steady invocation rate, this will put the telemetry POST in parallel with the handler processing, reducing our impact on the function lifecycle. I've also eliminated a case where we could have lost telemetry unnecessarily due to an invocation timeout. 
Finally, `defer` in a loop is not a great idea. It doesn't really accomplish what you want, and it does leak memory.
=> Harvest fix

examples/sam/distributedtracing/template.yml, examples/sam/java/README.md, examples/sam/java/template.yaml, examples/sam/node/README.md, examples/sam/node/template.yaml, examples/sam/python/README.md, examples/sam/python/template.yaml, examples/terraform/nodejs/README.md, examples/terraform/python/README.md
* fixes readmes, instructions didn't specify integrations as a sub command must be used
* adds cloudformation constraints to templates to advise that Image types are not supported
Resolves: fix/doc-and-small-adjs
=> doc: Fixes Readmes, Adds CF Constraint

config/config.go, config/config_test.go, main.go, util/logger.go
In addition to new relic, we also ship logs to an ELK stack.  We've noticed a large number of logs similar to the following in our lambdas:
`[NR_EXT] Sent 1/1 New Relic payload batches with 1 log events successfully in 331935.777ms (63ms to transmit 4.8kB)`
The goal of this PR is to allow users to disable extension logs.  This PR adds an environment variable `NEW_RELIC_EXTENSION_LOGS_ENABLED`.  The default behavior if unset is `true` (enabled).  When set to false, calls to logging functions will be ignored.  I've also added tests for this feature as well.
=> created new env var used to disable extension logs

Makefile, checks/runtime_check_test.go, checks/startup_check_test.go, lambda/logserver/logserver_test.go, main.go, main_test.go
Instead of shipping telemetry in a goroutine and relying on frequent invocations to successfully manage HTTP requests across invocations, just do the HTTP requests synchronously. This will reduce spurious retries, which can result in duplicate telemetry.
=> Fewer retries

telemetry/batch.go, telemetry/batch_test.go
Avoid runtime panics and unexpected changes in state by synchronizing access to the underlying data in a batch using a reader writer lock. This will have slight performance impact, but will prevent applications from being crashed.
=> Synchronize Batch with Reader Writer Lock

config/config.go, config/config_test.go, main.go, telemetry/client.go, telemetry/client_test.go
Users can now adjust how long the extension will attempt to retry
sending a data payload to New Relic using the environment variable
NEW_RELIC_DATA_COLLECTION_TIMEOUT. This gives customers more control
over the expected runtime of their application. Note that the extension may need to send more than one payload. The value of this timeout can be any
valid golang duration string. Some examples include 10s = 10 seconds;
500ms = 500 milliseconds; 1m = 1 minute. See
https://pkg.go.dev/maze.io/x/duration#ParseDuration for more info.
10s is the default.
=> Smarter Timeouts

.circleci/config.yml
Allows Circle CI to publish releases to GitHub directly
=> Update Release Key to Read Write Key

util/extension.go
This updates the file that tells the extension which version it is. Useful in debugging.
=> feat: Updated version to 2.3.5

telemetry/client.go
Due to latency issues in the EU region, we are extending the http timeout to 2 seconds, until the latency is back to normal. This may result in longer runtimes for applications with our layer in them, but will increase the chance data is sent to use successfully.
=> extend HTTP timeout to 2.4s 

examples/sam/python/newrelic_example_python/app.py
This PR updates Python example code to use `add_custom_attribute` instead of the deprecated `add_custom_parameter` API.
Related issue: #151
=> Update deprecated API in python lambda handler example.

README.md
This is a common tripping point for customers. Adding an explicit line to cover this in the documentation.
=> Telemetry Data Required Readme

checks/handler_check.go, checks/handler_check_test.go
We use [SST](https://sst.dev/) with the `commonjs` esbuild configuration.  This builds our lambdas into `.cjs` files.  This change allows `cjs` files within the extension
=> Allow CJS Files 

main.go, telemetry/batch_test.go, telemetry/client.go, telemetry/client_test.go, telemetry/request.go, telemetry/request_test.go
The telemetry/request.CompressedPayloadsForLogEvents() function has no base case for the case where the compressed payload is too large due to one single logsEvent being oversized. This causes an infinite recursive loop that will crash the extension. These changes patch that and cover this with a test case.
=> fix: infinite recursive loop

.github/workflows/build-release-assets.yml, .github/workflows/build-test-coverage.yml
- Add build for x86, unit test, & coverage
- Add build for arm architecture
- Add publish for x86 & arm such that .zip is uploaded to the released latest version of the extension
=> modify github workflow

.github/workflows/build-release-assets.yml
* remove softprops actions for release of binary
=> Workflow remove softprops

checks/sanity_check.go, checks/sanity_check_test.go
- newrelic-lambda-extension has [sanitycheck calls](https://github.com/newrelic/newrelic-lambda-extension/blob/88b35fe1b82de965f88d23c4ea3ace700143fd7a/checks/sanity_check.go#L25) to SSM parameter store that adds to production quotas for customers.
- Call SSM store when `NEW_RELIC_LICENSE_KEY_SSM_PARAMETER_NAME` var is set
=> remove SSM calls

checks/runtime_check.go, checks/sanity_check.go, checks/startup_check.go, checks/startup_check_test.go, main.go
Extension taking more than 2 minutes when in VPC without outbound traffic.
- Added timeout for calls to Secret & SSM Parameter Store
- Added context timeout for Sanity check calls for Secret and SSM Parameter Store
- Reduced timeout for github agent version check call to 2 seconds
=> Add timeouts

checks/handler_check.go
Issue with Warning: handler not set to New Relic layer wrapper newrelic-lambda-wrapper.handler
=> wrapper handler

checks/sanity_check.go, checks/sanity_check_test.go, credentials/credentials.go
NEW_RELIC_LICENSE_KEY Priority and bypass Secrets Manager check if NEW_RELIC_LICENSE_KEY is set
=> NR-281256 [ NEW_RELIC_LICENSE_KEY Priority check ]

README.md
Update readme for [github issue](https://github.com/newrelic/newrelic-lambda-extension/issues/124) No rule to make target `dist'
=> update readme build step

checks/runtime_config.go, examples/sam/ruby/README.md, examples/sam/ruby/deploy.sh, examples/sam/ruby/events/event.json, examples/sam/ruby/newrelic_example_ruby/app.rb, examples/sam/ruby/template.yaml, examples/sam/ruby/test/handler_test.rb, examples/terraform/ruby/README.md, examples/terraform/ruby/app.rb, examples/terraform/ruby/deploy.sh, examples/terraform/ruby/events/event.json, examples/terraform/ruby/lambda-assume-role-policy.json, examples/terraform/ruby/lambda-policy.json, examples/terraform/ruby/main.tf, examples/terraform/ruby/vars.tf
- Introduce runtime configuration values for Ruby (these do not yet power any automated checks)
- Add sam and terraform examples (these are pretty much straight ports of the Python examples)
=> Introduce support for Ruby

telemetry/client.go, telemetry/client_test.go
Reference [github issue](https://github.com/newrelic/newrelic-lambda-extension/issues/59)
This PR introduces environment variable to configure custom attributes or other metadata when sending logs directly using Extension. 
Use `NR_TAGS` &  `NR_ENV_DELIMITER` environment variables similar to the https://github.com/newrelic/aws-log-ingestion/issues/38 to add metadata to the logs.
=> Adds tags for logs

util/logger.go
Don't print any NR_EXT lines when `logsEnabled` is false, including the startup line.
=> fix: NR_EXT log lines

main.go, telemetry/client.go
- remove debug logs which are getting printed for each log line
- modify confusing message log - mainLoop: `blocking` is confusing customer
- add payloadSize to the log message `Telemetry client error: %s, payload size: %d bytes"`
=> Extension debug

README.md
Update `README.md` for feature https://github.com/newrelic/newrelic-lambda-extension/pull/224
Reference https://github.com/newrelic/newrelic-lambda-extension/issues/59
The feature introduced environment variable to configure custom attributes or other metadata when sending logs directly using Extension. The PR updates the `README.md` with relevant environment variables that need to be set example - `NR_TAGS` & `NR_ENV_DELIMITER`
=> update NR_TAGS in readme

config/config.go, config/config_test.go
- Solves [github issue](https://github.com/newrelic/newrelic-lambda-extension/issues/215) related to Extension not handling some environment variables
- Extension should be a no-op if NEW_RELIC_ENABLED=`false` or NEW_RELIC_AGENT_ENABLED=`false`
=> NEW_RELIC_ENABLED  Env issue 

config/config.go, config/config_test.go
- Go Agent uses [ParseBool](https://github.com/newrelic/go-agent/blob/6c84bcfba282b0c2984582cff8bca8eb9a3e1ee0/v3/newrelic/config_options.go#L413) for some env variables.
- updating `NEW_RELIC_ENABLED`  as customer would like to use similar feature in lambda environment
- [Github issue link](https://github.com/newrelic/newrelic-lambda-extension/issues/215)
=> update NEW_RELIC_ENABLED to Env bool 

checks/startup_check.go, checks/startup_check_test.go, config/config.go, config/config_test.go, main.go
During the star-tup, Extension performs following checks:
Runtime check, Agent version check, Handler check, Sanity check, Vendor check. The feature, allow bypassing of Extension checks using env var `NEW_RELIC_IGNORE_EXTENSION_CHECKS`
- By default, all the above-mentioned start-up checks will be enabled as they help new customers onboarding smoothly.
- Environment variable `NEW_RELIC_IGNORE_EXTENSION_CHECKS` - a string of comma separated values:
- To disable specific checks: `handler`, `agent`, `sanity`, `vendor`
- To disable all the checks: `all`
- the `NEW_RELIC_IGNORE_EXTENSION_CHECKS` string is case insensitive
=> Run Extension checks conditionally 

README.md
We have migrated from using Circle CI to Github Actions for building and Releasing Extension assets.
=> update circleCI badge to github actions badge

README.md, config/config.go, lambda/logserver/logserver.go, main.go
- Subscribe to `Extension` log EventType in `subscriptionRequest` to be send to Logs API to receive Extension log events
- Create env var `NEW_RELIC_EXTENSION_SEND_EXTENSION_LOGS` to enable sending Extension log events to New Relic
- Send the Extension logs to FunctionLogs channel which receives all logs and sends it as log Payload to New Relic Log endpoint
- Update Readme
=> Send Extension log events

lambda/logserver/logserver.go, main.go
- Logs API provides event type = `platform.fault` as mentioned [here](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-logs-api.html#:~:text=end%2C%20and-,platform.fault,-.)
- Shutdown event is sent to Extension for the reason mentioned [here](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-extensions-api.html#runtimes-extensions-api-failure)
=> Record platform fault which triggers shutdown

.github/workflows/build-test-coverage.yml, codecov.yml, coverage.sh
- Updated GitHub actions workflow to run Codecov coverage as a task
- We can see that after ignoring examples folder the codecov coverage improved from ` 78.46%` to `79.71%`
=> Modify workflow to upload Codecov report

local_testing/publish.sh
- Currently, we can only test Lambda with Python runtime for local testing
- Adding publish script to publish Extension only Lambda Layers that can be used for Lambda with Golang runtime
=> add publish script for extension only Lambda Layer in local testing

main.go, telemetry/batch.go, telemetry/batch_test.go
- This helps to avoid calling the ExtractTraceID function if telemetry bytes is not present.
#182
=> chore: Updating Trace.id Conditions

apm/collector.go, apm/connect.go, lambda/extension/api/api.go, lambda/extension/client/client.go, main.go
Add fields such as `aws.arn`, `aws.region`, `aws.accountId`, and  `aws.functionName` under `utilization` for connect call
=> add vendor utilization data for connect request

.github/workflows/build-release-assets.yml, .github/workflows/build-test-coverage.yml
- While testing release of test Extension, received error message - `This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15`
- We can see that Ubuntu 20.04 is deprecated in the [GitHub runner-images](https://github.com/actions/runner-images?tab=readme-ov-file#available-images)
=> update ubuntu runner

lambda/logserver/logserver.go, lambda/logserver/logserver_test.go
- The Mutex lock complements the WaitGroup [added by [PR](https://github.com/newrelic/newrelic-lambda-extension/pull/310)] by providing thread-safe access to the `shutdown state`, allowing handlers to `gracefully abort` processing when shutdown is initiated while preventing `race conditions`. This ensures `no new logs` are sent to closed channels during the `shutdown process`, preventing potential panics.
#267
=> feat: added logic to check the shutdown of logserver

README.md
- According to the ticket, we noticed that `--enable-license-key-secret` is set to true by default, so it's not required to specify it during integrations installation.
[NR-404207]: https://new-relic.atlassian.net/browse/NR-404207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: updated Readme

go.mod, util/extension.go
- Add `godebug` to resolve AWS Firewall issue due to go experimental key exchange mechanism X25519Kyber768Draft00
- Resolves GitHub issue #313
=> Add godebug to resolve AWS Firewall issue

.github/workflows/release-testing.yml, Makefile, release-testing/publish-layer.sh
Currently, testing the Lambda extension requires a manual process of building, publishing to AWS, and invoking a Lambda. This is slow, error-prone, and not automated.
This PR introduces a new GitHub Actions workflow to automate the entire end-to-end integration testing process. This will allow developers to quickly and reliably test changes to the extension with a single click before a release. Along with cold start and warm start measurements which can be seen from newrelic dashboard.
This PR introduces the following changes:
**New GitHub Actions Workflow**: Adds a new workflow at .github/workflows/release-testing.yml. This workflow is manually triggered and contains two jobs:
**publish-layers**: Compiles the Go extension using the Makefile, creates x86_64 and arm64 Lambda Layers, …
=> feat: Add GitHub Actions workflow for publishing Lambda layers

apm/internal_app.go, apm/internal_app_test.go
The `NEW_RELIC_HOST` backoff times were updated for 3 retries to approximately: 200, 500, 900 ms.
```
[NR_EXT] Retry 1 took 207.985511ms (including backoff of 200ms)
[NR_EXT] Retry 2 took 728.646959ms (including backoff of 500ms)
[NR_EXT] Retry 3 took 1.649241537s (including backoff of 900ms)
```
[NR-428800]: https://new-relic.atlassian.net/browse/NR-428800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Update backoff duration for NEW_RELIC_HOST
